// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZD8u2swb-aisZHgXiIiMFIb4Q7ar_mBo',
    appId: '1:1086686791372:web:af11118a277ca22c0ca469',
    messagingSenderId: '1086686791372',
    projectId: 'threads-jun',
    authDomain: 'threads-jun.firebaseapp.com',
    storageBucket: 'threads-jun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi6ojnKM9hIBHMRFYk4WmCGU1mGdmAKWQ',
    appId: '1:1086686791372:android:acde08c4086c1a030ca469',
    messagingSenderId: '1086686791372',
    projectId: 'threads-jun',
    storageBucket: 'threads-jun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvIyaVDN1PME4bznQVeC0ercQ588NGyw',
    appId: '1:1086686791372:ios:66d5af2a3cc2af590ca469',
    messagingSenderId: '1086686791372',
    projectId: 'threads-jun',
    storageBucket: 'threads-jun.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );
}
